
name: create-bin-multiplat

on:
  push:
    tags:
      - '*'

jobs:
  generate:

    name: Publish ${{ matrix.asset_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: tufast_matching_tool-linux-amd64
            executable_path: "dist/tufast_matching_tool-linux-amd64"
          - os: windows-latest
            asset_name: tufast_matching_tool-windows-amd64
            executable_path: "dist\\tufast_matching_tool-windows-amd64.exe"
          - os: macos-latest
            asset_name: tufast_matching_tool-macos
            executable_path: "dist/tufast_matching_tool-macos"

    steps:

    - name: Checkout the repository
      uses: actions/checkout@master
      with:
        lfs: 'true'

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip pyinstaller pillow
        python3 -m pip list
      env:
        PYINSTALLER_COMPILE_BOOTLOADER: 1 

    - name: Install matching_tool
      run: |
        python3 -m pip install .
        python3 -m pip list

    - name: Check that matching_tool is installed
      run: |
        python3 -m pip install .
        python3 -m pip list
        python3 -c 'from tufast_matching_tool import __version__; print(__version__)'

    - name: Build binary
      run: |
        pyinstaller --onefile --windowed --add-data "tufast_img.ico:." --icon "tufast_img.ico" --name ${{ matrix.asset_name }} src/run.py
        
    - name: Upload
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ matrix.executable_path }}